-- MySQL Script generated by MySQL Workbench
-- Fr 22 Dez 2017 11:59:08 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema woche7db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema woche7db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `woche7db` DEFAULT CHARACTER SET utf8 ;
USE `woche7db` ;

-- -----------------------------------------------------
-- Table `woche7db`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `woche7db`.`Student` (
  `idStudent` INT NOT NULL AUTO_INCREMENT,
  `Vorname` VARCHAR(100) NOT NULL DEFAULT 'VORNAME',
  `Nachname` VARCHAR(100) NOT NULL DEFAULT 'NACHNAME',
  `githubUsername` VARCHAR(100) NOT NULL DEFAULT 'GITHUBUSERNAME',
  `Beschreibung` TEXT NULL DEFAULT 'TEXT',
  PRIMARY KEY (`idStudent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `woche7db`.`Gruppe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `woche7db`.`Gruppe` (
  `idGruppe` INT NOT NULL AUTO_INCREMENT,
  `Gruppenname` VARCHAR(100) NOT NULL DEFAULT 'GRUPPENNAME',
  `minMitglieder` INT NOT NULL DEFAULT 1,
  `maxMitglieder` INT NOT NULL DEFAULT 8,
  `Regelsatz` VARCHAR(100) NOT NULL DEFAULT 'GRUPPENREGELN',
  `Frist` INT NOT NULL DEFAULT FRISTINDAYS,
  `Gruppengründer` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idGruppe`),
  UNIQUE INDEX `Gruppenname_UNIQUE` (`Gruppenname` ASC),
  INDEX `Gruppengründer_idx` (`Gruppengründer` ASC),
  CONSTRAINT `Gruppengründer`
    FOREIGN KEY (`Gruppengründer`)
    REFERENCES `woche7db`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `woche7db`.`Teilnahme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `woche7db`.`Teilnahme` (
  `Student_idStudent` INT NOT NULL,
  `Gruppe_idGruppe` INT NOT NULL,
  PRIMARY KEY (`Student_idStudent`, `Gruppe_idGruppe`),
  INDEX `fk_Student_has_Gruppe_Gruppe2_idx` (`Gruppe_idGruppe` ASC),
  INDEX `fk_Student_has_Gruppe_Student1_idx` (`Student_idStudent` ASC),
  CONSTRAINT `fk_Student_has_Gruppe_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `woche7db`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Gruppe_Gruppe2`
    FOREIGN KEY (`Gruppe_idGruppe`)
    REFERENCES `woche7db`.`Gruppe` (`idGruppe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `woche7db`.`Bewerbung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `woche7db`.`Bewerbung` (
  `Student_idStudent` INT NOT NULL,
  `Gruppe_idGruppe` INT NOT NULL,
  `Ablauf` DATETIME NOT NULL,
  `Status` TINYINT(4) NOT NULL DEFAULT 0,
  `ErstellungsZeitpunkt` DATETIME NOT NULL,
  `Nachricht` TEXT NULL,
  PRIMARY KEY (`Student_idStudent`, `Gruppe_idGruppe`),
  INDEX `fk_Student_has_Gruppe1_Gruppe1_idx` (`Gruppe_idGruppe` ASC),
  INDEX `fk_Student_has_Gruppe1_Student1_idx` (`Student_idStudent` ASC),
  CONSTRAINT `fk_Student_has_Gruppe1_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `woche7db`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Gruppe1_Gruppe1`
    FOREIGN KEY (`Gruppe_idGruppe`)
    REFERENCES `woche7db`.`Gruppe` (`idGruppe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `woche7db`.`Arbeitsprobe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `woche7db`.`Arbeitsprobe` (
  `idtable1` INT NOT NULL,
  `link` VARCHAR(250) NOT NULL DEFAULT 'LINKTOGITHUBPROJECT',
  `projektName` VARCHAR(100) NULL DEFAULT 'PROJEKTNAME',
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `woche7db`.`Student_has_Arbeitsprobe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `woche7db`.`Student_has_Arbeitsprobe` (
  `Student_idStudent` INT NOT NULL,
  `Arbeitsprobe_idtable1` INT NOT NULL,
  PRIMARY KEY (`Student_idStudent`, `Arbeitsprobe_idtable1`),
  INDEX `fk_Student_has_Arbeitsprobe_Arbeitsprobe1_idx` (`Arbeitsprobe_idtable1` ASC),
  INDEX `fk_Student_has_Arbeitsprobe_Student1_idx` (`Student_idStudent` ASC),
  CONSTRAINT `fk_Student_has_Arbeitsprobe_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `woche7db`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Arbeitsprobe_Arbeitsprobe1`
    FOREIGN KEY (`Arbeitsprobe_idtable1`)
    REFERENCES `woche7db`.`Arbeitsprobe` (`idtable1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
